Partial fix for partial 1080
 0:33.35 error[E0277]: the trait bound `Arc<str>: AsRef<OsStr>` is not satisfied
 0:33.35     --> C:\Users\Admin\Documents\GitHub\r3dfox-old\third_party\rust\cc\src\lib.rs:2065:25
 0:33.35      |
 0:33.35 2065 |                 cmd.arg(flag);
 0:33.35      |                     --- ^^^^ the trait `AsRef<OsStr>` is not implemented for `Arc<str>`, which is required by `&Arc<str>: AsRef<OsStr>`
 0:33.35      |                     |
 0:33.35      |                     required by a bound introduced by this call
 0:33.35      |
 0:33.35      = help: the trait `AsRef<str>` is implemented for `Arc<str>`
 0:33.35      = help: for that trait implementation, expected `str`, found `OsStr`
 0:33.35      = note: required for `&Arc<str>` to implement `AsRef<OsStr>`
 0:33.35 note: required by a bound in `Command::arg`
 0:33.36     --> C:\Users\Admin\Documents\GitHub\eRust\library\std\src\process.rs:691:5
 0:33.36 error[E0271]: type mismatch resolving `<&Vec<Arc<Path>> as IntoIterator>::Item == &PathBuf`
 0:33.36     --> C:\Users\Admin\Documents\GitHub\r3dfox-old\third_party\rust\cc\src\lib.rs:2072:24
 0:33.36      |
 0:33.36 2072 |                 .chain(&self.objects)
 0:33.36      |                  ----- ^^^^^^^^^^^^^ expected `&PathBuf`, found `&Arc<Path>`
 0:33.36      |                  |
 0:33.36      |                  required by a bound introduced by this call
 0:33.36      |
 0:33.36      = note: expected reference `&PathBuf`
 0:33.36                 found reference `&Arc<Path>`
 0:33.36 note: required by a bound in `std::iter::Iterator::chain`
 0:33.36     --> C:\Users\Admin\Documents\GitHub\eRust\library\core\src\iter\traits\iterator.rs:521:5
 0:33.36 error[E0599]: the method `map` exists for struct `Chain<Iter<'_, PathBuf>, Iter<'_, Arc<Path>>>`, but its trait bounds were not satisfied
 0:33.36     --> C:\Users\Admin\Documents\GitHub\r3dfox-old\third_party\rust\cc\src\lib.rs:2073:18
 0:33.36      |
 0:33.36 2070 |               let estimated_command_line_len = objects
 0:33.36      |  ______________________________________________-
 0:33.36 2071 | |                 .iter()
 0:33.36 2072 | |                 .chain(&self.objects)
 0:33.36 2073 | |                 .map(|a| a.as_os_str().len())
 0:33.36      | |                 -^^^ method cannot be called on `Chain<Iter<'_, PathBuf>, Iter<'_, Arc<Path>>>` due to unsatisfied trait bounds
 0:33.36      | |_________________|
 0:33.36      |
 0:33.36      |
 0:33.36      = note: the following trait bounds were not satisfied:
 0:33.36              `<std::slice::Iter<'_, Arc<Path>> as Iterator>::Item = &PathBuf`
 0:33.36              which is required by `std::iter::Chain<std::slice::Iter<'_, PathBuf>, std::slice::Iter<'_, Arc<Path>>>: Iterator`
 0:33.36              `std::iter::Chain<std::slice::Iter<'_, PathBuf>, std::slice::Iter<'_, Arc<Path>>>: Iterator`
 0:33.36              which is required by `&mut std::iter::Chain<std::slice::Iter<'_, PathBuf>, std::slice::Iter<'_, Arc<Path>>>: Iterator`
 0:33.36 error[E0271]: type mismatch resolving `<&Vec<Arc<Path>> as IntoIterator>::Item == &PathBuf`
 0:33.36     --> C:\Users\Admin\Documents\GitHub\r3dfox-old\third_party\rust\cc\src\lib.rs:2077:49
 0:33.36      |
 0:33.36 2077 |                 for arg in objects.iter().chain(&self.objects) {
 0:33.36      |                                           ----- ^^^^^^^^^^^^^ expected `&PathBuf`, found `&Arc<Path>`
 0:33.36      |                                           |
 0:33.37      |                                           required by a bound introduced by this call
 0:33.37      |
 0:33.37      = note: expected reference `&PathBuf`
 0:33.37                 found reference `&Arc<Path>`
 0:33.37 note: required by a bound in `std::iter::Iterator::chain`
 0:33.37     --> C:\Users\Admin\Documents\GitHub\eRust\library\core\src\iter\traits\iterator.rs:521:5
 0:33.37 error[E0271]: expected `Iter<'_, Arc<Path>>` to be an iterator that yields `&PathBuf`, but it yields `&Arc<Path>`
 0:33.37     --> C:\Users\Admin\Documents\GitHub\r3dfox-old\third_party\rust\cc\src\lib.rs:2077:28
 0:33.37      |
 0:33.37 2077 |                 for arg in objects.iter().chain(&self.objects) {
 0:33.37      |                            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ expected `&Arc<Path>`, found `&PathBuf`
 0:33.37      |
 0:33.37      = note: expected reference `&Arc<Path>`
 0:33.37                 found reference `&PathBuf`
 0:33.37      = note: required for `std::iter::Chain<std::slice::Iter<'_, PathBuf>, std::slice::Iter<'_, Arc<Path>>>` to implement `Iterator`
 0:33.37      = note: required for `std::iter::Chain<std::slice::Iter<'_, PathBuf>, std::slice::Iter<'_, Arc<Path>>>` to implement `IntoIterator`
 0:33.37 error[E0271]: expected `Iter<'_, Arc<Path>>` to be an iterator that yields `&PathBuf`, but it yields `&Arc<Path>`
 0:33.37     --> C:\Users\Admin\Documents\GitHub\r3dfox-old\third_party\rust\cc\src\lib.rs:2077:28
 0:33.37      |
 0:33.37 2077 |                 for arg in objects.iter().chain(&self.objects) {
 0:33.37      |                            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ expected `&Arc<Path>`, found `&PathBuf`
 0:33.37      |
 0:33.37      = note: expected reference `&Arc<Path>`
 0:33.37                 found reference `&PathBuf`
 0:33.37      = note: required for `std::iter::Chain<std::slice::Iter<'_, PathBuf>, std::slice::Iter<'_, Arc<Path>>>` to implement `Iterator`
 0:33.37 error[E0277]: the trait bound `Arc<Path>: AsRef<OsStr>` is not satisfied
 0:33.37     --> C:\Users\Admin\Documents\GitHub\r3dfox-old\third_party\rust\cc\src\lib.rs:2106:36
 0:33.37      |
 0:33.37 2106 |                 cmd.args(&objects).args(&self.objects);
 0:33.37      |                                    ^^^^ the trait `AsRef<OsStr>` is not implemented for `Arc<Path>`, which is required by `&Arc<Path>: AsRef<OsStr>`
 0:33.37      |
 0:33.37      = help: the trait `AsRef<Path>` is implemented for `Arc<Path>`
 0:33.37      = help: for that trait implementation, expected `Path`, found `OsStr`
 0:33.38      = note: required for `&Arc<Path>` to implement `AsRef<OsStr>`
 0:33.38 note: required by a bound in `Command::args`
 0:33.38     --> C:\Users\Admin\Documents\GitHub\eRust\library\std\src\process.rs:736:5
 0:33.38 error[E0277]: the trait bound `Arc<Path>: AsRef<OsStr>` is not satisfied
 0:33.38     --> C:\Users\Admin\Documents\GitHub\r3dfox-old\third_party\rust\cc\src\lib.rs:2158:55
 0:33.38      |
 0:33.38 2158 |             run(ar.arg("cqs").arg(dst).args(&objects).args(&self.objects), &cmd)?;
 0:33.38      |                                                       ^^^^ the trait `AsRef<OsStr>` is not implemented for `Arc<Path>`, which is required by `&Arc<Path>: AsRef<OsStr>`
 0:33.38      |
 0:33.38      = help: the trait `AsRef<Path>` is implemented for `Arc<Path>`
 0:33.38      = help: for that trait implementation, expected `Path`, found `OsStr`
 0:33.38      = note: required for `&Arc<Path>` to implement `AsRef<OsStr>`
 0:33.38 note: required by a bound in `Command::args`
 0:33.38     --> C:\Users\Admin\Documents\GitHub\eRust\library\std\src\process.rs:736:5
 0:33.45 Some errors have detailed explanations: E0271, E0277, E0599.
 0:33.45 For more information about an error, try `rustc --explain E0271`.
 0:33.53 error: could not compile `cc` (lib) due to 8 previous errors