Do not add the clang runtime directory to LIB during configure
I assume old clang or whatever does not support .strip() here.
`AttributeError: 'NoneType' object has no attribute 'strip'`